### ISSUE TITLE
 The lessons.tar contains only images in png format

### ISSUE THREAD

**Issue by Iximiel** [plumed-school/plumed-school#2]
I think the [line](https://github.com/plumed-school/plumed-school/blob/fa792a7edeebc1472edfc1cb85579fb7e9491fc2/.github/workflows/main.yml#L87)
`tar cf lessons.tar $(find . -name "*.pdf") $(find . -name "*.png") $(find . -name "*.md") $(find . -name "*.stdout.txt.zip") $(find . -name "*.stderr.txt.zip") $(find . -name "*badge.svg") $(find . -name "*.html") _data/*.yml _data/*.json`

in the CI does not upload images that are not pngs

**Comment by gtribello** [comment]
What file types should be added to that command?

**Comment by Iximiel** [comment]
For my lesson I used gif and svg.

But I think people will also want to use jpg, jpeg, or maybe webp (or some other format that I am not thinking about right now).

And on the other hand, does `find` distinguish between ".PNG" and ".png"?

**Comment by gtribello** [comment]
OK, I have added that it can find GIF and SVG files and upload them, so your tutorial will work.  

For the rest, we can update it as and when people say they need additional things.
